### ISSUE TITLE
TODO: Test suit for sync 

### ISSUE THREAD

**Issue by Isan-Rivkin** [enigmampc/enigma-p2p#14]
**Sunny day scenario**
In this case the `Provider` databset can always stay the same, only the `Receiver` side should load the correct db.
- [x] Sync from scratch 
- [x] Sync from mid-with-all-addresses
- [x] Sync from mid-with-some-addresses

**Rainy day scenario**
This case is more complex in terms of db and will be addressed later.
- [ ] Provider error on start 
- [ ] Provider error mid way 
- [ ] Provider fauly mid way 
- [ ] DOS on bandwith from PRovider
