### ISSUE TITLE
TODO before sync is done 

### ISSUE THREAD

**Issue by Isan-Rivkin** [enigmampc/enigma-p2p#17]
### **SyncMessageBuilder:**

- [ ] Change all `NoValidation` methods to have validation but **no callbacks**.
### **Streams General :**
- [x] handle errors gracefully in all streams. (source,through's and sinks).
### **Provider streams:**
- [x] **requestParserStream** : change stop calling the parser `_fakeRequestParser` name
- [x] **toNetworkParser** : change `_fakeParseFromDbToNetwork` name

### **Receiver streams:**

- [x] **verificationStream** implement ethereum validation with (@lenak25 potential TODO)
- [x] **throughDbStream** imlement write to `db` (using `core-ipc`)
- [x] **Map + Collect** parse the db results to something that summarize the sync status. 
### **Actions:**
- [x] **IdentifyMissingStatesAction** :
    - [x] integrate @lenak25 implementation for missing states from remote. 
    - [x] integrate the `useCache` option

- [x] **FindContentProviderAction** : remove `isEngCid` legacy flag 

- [x] **TryReceiveAllAction** : define what the `final states result` is

### **Tests:**
#14

**Comment by Isan-Rivkin** [comment]
The only thing left to do:
> Change all NoValidation methods to have validation but no callbacks.
Add validation, use [this](https://github.com/enigmampc/enigma-p2p/blob/master/src/core/core_server_mock/core_server.js) example.
