### ISSUE TITLE
Left to do 

### ISSUE THREAD

**Issue by Isan-Rivkin** [enigmampc/enigma-p2p#74]
- [x] #94 fix bug @Isan-Rivkin 
- [x] #83 @elichai 
- [x] #17 (@Isan-Rivkin , done partially - enough to meet internal release goals)
- [x] integrate ethereum api @lenak25 (pr #81)
    - [x] verify result 
    - [x] verify task 
    - [x] new epoch -> ptt  
- [x] single config @Isan-Rivkin (pr #91)
- [x] announce all when sync result @Isan-Rivkin 
- [x] sync-> updateDb @Isan-Rivkin 
- [x] Init pipelines @AvishaiW 
    - [x] health check 
    - [x] register,deposit,login
- [x] API/CLI: logout,login,withdraw @lenak25 (pr #95)
- [x] Persistent discovery @Isan-Rivkin (pr #99 )
- [x] add getResult jsonrpc endpoint #82 @Isan-Rivkin 
- [x] align with enigma-contract @lenak25  
- [ ] <strike> Slow sync </strike>
- [x] impl _verifyTaskCreateParams() method @lenak25 (pr #147 )

**Comment by lenak25** [comment]
All tasks are done, closing
